### ISSUE TITLE
Keyboard simulation, or other means, to enter large files, on Sharp PCs

### ISSUE THREAD

**Issue by ffxx68** [pockemul/PockEmul_Issues#5]
Hi, is there a way to enter large files on emulated Sharp PCs (I'm using a PC-1403).
This is the only way one can really emulate some real program, or am I missing something?
Thanks, and keep up with this great work!

**Comment by pockemul** [comment]
Hi,
The keyboard simulator is currently the only way to enter large programs on the handheld.
In the next version, available in a few days, there is an option to load the keyboard simulator from a text file.
You can, meanwhile, open your file in an external editor and copy/paste the text into the keyboard simulator.

In my development environment, PockEmul is able to emulate the tape interface. I can directly load a WAV file and load it into the handheld with the Basic LOAD statement. this feature is not released because it is quite unstable. Actually, I created the keyboard simulator to bypass tape emulation.

The Tape feature is in my roadmap anyway.

**Comment by ffxx68** [comment]
Ok, if I have to wait next version with the keyboard simulator, I don't understand when you say "You can, meanwhile ... paste the text into the keyboard simulator". Can I do it now on v2.3.0?

**Comment by ffxx68** [comment]
Is it a pay-only feature, by chance?

**Comment by pockemul** [comment]
Which release are you using ? Android or Windows ?

**Comment by ffxx68** [comment]
Windows 2.3.0. In the configuratoin I can only see these options
![image](https://user-images.githubusercontent.com/659557/161089452-ba64a7cc-9cad-4a09-b467-bf18b0d0a1c2.png)

**Comment by pockemul** [comment]
If you use v2.3.0 on Windows, you are limited to the 6 free models with no extended features.
To activate all models and features (including the Keyboard Simulator"), you have to subscribe on pockemul Android and activate your Windows installation. 
It is explained here: https://pockemul.com/index.php/2020/11/10/pockemul-2-1-0-one-more-step-to-pockemul-everywhere/

**Comment by ffxx68** [comment]
You managed to convince me! I purchased a subscription :)
