### ISSUE TITLE
Keyboard simulator stops when Windows app loses focus

### ISSUE THREAD

**Issue by ffxx68** [pockemul/PockEmul_Issues#7]
Keyboard key entry shouldn't be stopped when pockemul doesn't have focus.
Now I have to leave app active until key entry is complete (which could take very long time).

**Comment by pockemul** [comment]
I think it is because, by default, PockEmul freeze itself when it is not in foreground.
This behaviour was introduce at the beginning to preserve battery life on mobile devices.
In the settings you have the option to force "keep running in background".
This should fixe your issue.
I must admit, it should be the default behaviour on Windows ...

**Comment by ffxx68** [comment]
got it, thanks
